development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  host: localhost
  username: postgres
  password: password
  
Production:  
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: postgres
  password: password
